name: Daily Product Hunt Scraper

on:
  schedule:
    # Run daily at 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape_product_hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Product Hunt scraper
        env:
          PH_CLIENT_ID: ${{ secrets.PH_CLIENT_ID }}
          PH_CLIENT_SECRET: ${{ secrets.PH_CLIENT_SECRET }}
        run: |
          # Run with human behavior simulation to avoid rate limits
          python run_daily.py --run_once
          
          # Check if data was collected successfully
          if [ ! -f $(find daily_data -name "product_hunt_data.csv" | head -1) ]; then
            echo "Warning: No data was collected in the first run. Trying again with disabled human simulation..."
            # Fallback to faster scraping if human simulation didn't work
            python run_daily.py --run_once --no-human-simulation
          fi

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: product-hunt-data
          path: daily_data/
          retention-days: 30

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add daily_data
          git commit -m "Update Product Hunt data ($(date +'%Y-%m-%d'))" || echo "No changes to commit"
          git push 